/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package othello.view;

/**
 *
 * @author Foster
 */
public class CrearPartidaUI extends javax.swing.JFrame {

    /**
     * Creates new form CrearPartidaUI
     */
    public CrearPartidaUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Jugador1 = new javax.swing.JRadioButton();
        IA1 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        labelJ1 = new javax.swing.JLabel();
        Combo1 = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        RadioBlanco1 = new javax.swing.JRadioButton();
        RadioNegro1 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        Jugador2 = new javax.swing.JRadioButton();
        IA2 = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        labelJ2 = new javax.swing.JLabel();
        Combo2 = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        RadioBlanco2 = new javax.swing.JRadioButton();
        RadioNegro2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Partida");

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jugador 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel4.setLayout(new java.awt.GridLayout(2, 2));

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        buttonGroup1.add(Jugador1);
        Jugador1.setSelected(true);
        Jugador1.setText("Jugador");
        jPanel6.add(Jugador1);

        buttonGroup1.add(IA1);
        IA1.setText("IA");
        IA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IA1ActionPerformed(evt);
            }
        });
        jPanel6.add(IA1);

        jPanel4.add(jPanel6);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.PAGE_AXIS));

        labelJ1.setText("jLabel2");
        labelJ1.setAlignmentX(0.5F);
        jPanel7.add(labelJ1);

        Combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Combo1.setMaximumSize(new java.awt.Dimension(57, 20));
        jPanel7.add(Combo1);

        jPanel4.add(jPanel7);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel3.setText("Selecciona Color");
        jPanel8.add(jLabel3);

        buttonGroup2.add(RadioBlanco1);
        RadioBlanco1.setSelected(true);
        RadioBlanco1.setText("Blanco");
        jPanel8.add(RadioBlanco1);

        buttonGroup2.add(RadioNegro1);
        RadioNegro1.setText("Negro");
        RadioNegro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioNegro1ActionPerformed(evt);
            }
        });
        jPanel8.add(RadioNegro1);

        jPanel4.add(jPanel8);

        jPanel2.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jugador 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel5.setLayout(new java.awt.GridLayout(2, 2));

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.PAGE_AXIS));

        buttonGroup3.add(Jugador2);
        Jugador2.setSelected(true);
        Jugador2.setText("Jugador");
        jPanel9.add(Jugador2);

        buttonGroup3.add(IA2);
        IA2.setText("IA");
        jPanel9.add(IA2);

        jPanel5.add(jPanel9);

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.PAGE_AXIS));

        labelJ2.setText("jLabel1");
        labelJ2.setAlignmentX(0.5F);
        jPanel10.add(labelJ2);

        Combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Combo2.setMaximumSize(new java.awt.Dimension(57, 20));
        jPanel10.add(Combo2);

        jPanel5.add(jPanel10);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel4.setText("jLabel4");
        jPanel11.add(jLabel4);

        buttonGroup4.add(RadioBlanco2);
        RadioBlanco2.setText("Blanco");
        jPanel11.add(RadioBlanco2);

        buttonGroup4.add(RadioNegro2);
        RadioNegro2.setSelected(true);
        RadioNegro2.setText("Negro");
        jPanel11.add(RadioNegro2);

        jPanel5.add(jPanel11);

        jPanel2.add(jPanel5);

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escenario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IA1ActionPerformed

    private void RadioNegro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioNegro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioNegro1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combo1;
    private javax.swing.JComboBox<String> Combo2;
    private javax.swing.JRadioButton IA1;
    private javax.swing.JRadioButton IA2;
    private javax.swing.JRadioButton Jugador1;
    private javax.swing.JRadioButton Jugador2;
    private javax.swing.JRadioButton RadioBlanco1;
    private javax.swing.JRadioButton RadioBlanco2;
    private javax.swing.JRadioButton RadioNegro1;
    private javax.swing.JRadioButton RadioNegro2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel labelJ1;
    private javax.swing.JLabel labelJ2;
    // End of variables declaration//GEN-END:variables
    
}

