package othello.view;

import java.awt.Image;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Aleix
 */
public class MenuPrincipalUI extends javax.swing.JFrame {

    private CtrlView iCtrlView;
    
    /**
     * Creates new form MenuPrincipalUI
     */
    public MenuPrincipalUI(CtrlView pCtrlView) {
        iCtrlView = pCtrlView;
        this.setTitle("Othello App");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        try {
            Image imageResized = ImageIO.read(new File("src/main/java/resources/ranking.png")).getScaledInstance(50, 50, Image.SCALE_DEFAULT);
            btn_ranking.setIcon(new ImageIcon(imageResized));
            Image image = ImageIO.read(new File("src/main/java/resources/OthelloWindowIcon.png"));
            this.setIconImage(image);
            
        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        btn_ranking = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_exit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_perfil = new javax.swing.JButton();
        btn_jugar = new javax.swing.JButton();
        btn_escenario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(537, 425));
        setPreferredSize(new java.awt.Dimension(537, 425));

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btn_ranking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rankingActionPerformed(evt);
            }
        });
        jPanel4.add(btn_ranking);

        getContentPane().add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btn_exit.setText("EXIT");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel3.add(btn_exit);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        btn_perfil.setText("PERFIL");
        btn_perfil.setMaximumSize(new java.awt.Dimension(200, 60));
        btn_perfil.setMinimumSize(new java.awt.Dimension(200, 60));
        btn_perfil.setPreferredSize(new java.awt.Dimension(200, 60));
        btn_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perfilActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(btn_perfil, gridBagConstraints);

        btn_jugar.setText("JUGAR");
        btn_jugar.setMaximumSize(new java.awt.Dimension(180, 60));
        btn_jugar.setMinimumSize(new java.awt.Dimension(180, 60));
        btn_jugar.setPreferredSize(new java.awt.Dimension(180, 60));
        btn_jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jugarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        jPanel2.add(btn_jugar, gridBagConstraints);

        btn_escenario.setText("ESCENARIO");
        btn_escenario.setMaximumSize(new java.awt.Dimension(180, 60));
        btn_escenario.setMinimumSize(new java.awt.Dimension(180, 60));
        btn_escenario.setPreferredSize(new java.awt.Dimension(180, 60));
        btn_escenario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_escenarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(btn_escenario, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perfilActionPerformed
        iCtrlView.changeWindow("MenuPerfil");
    }//GEN-LAST:event_btn_perfilActionPerformed

    private void btn_jugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jugarActionPerformed
        iCtrlView.changeWindow("CrearPartida");
    }//GEN-LAST:event_btn_jugarActionPerformed

    private void btn_escenarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_escenarioActionPerformed
        iCtrlView.changeWindow("CrearPartida");
    }//GEN-LAST:event_btn_escenarioActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_rankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rankingActionPerformed
        iCtrlView.changeWindow("Ranking");
    }//GEN-LAST:event_btn_rankingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_escenario;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_jugar;
    private javax.swing.JButton btn_perfil;
    private javax.swing.JButton btn_ranking;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
