/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package othello.view;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author FRANCO
 */
public class panelPerfil extends javax.swing.JPanel implements ActionListener{

    /**
     * Creates new form panelPerfil
     */
    public panelPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_crearPerfil = new javax.swing.JButton();
        btn_consultarEstadistica = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_atras = new javax.swing.JButton();

        jPanel2.setMinimumSize(new java.awt.Dimension(537, 425));
        jPanel2.setPreferredSize(new java.awt.Dimension(537, 425));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_crearPerfil.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_crearPerfil.setText("Crear Perfil");
        btn_crearPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearPerfilActionPerformed(evt);
            }
        });
        jPanel2.add(btn_crearPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 230, 50));

        btn_consultarEstadistica.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_consultarEstadistica.setText("Consultar Estadistica");
        btn_consultarEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarEstadisticaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_consultarEstadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 230, 50));

        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_exit.setText("EXIT");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel2.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 375, 90, 30));

        btn_atras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_atras.setText("ATRAS");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });
        jPanel2.add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 375, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crearPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearPerfilActionPerformed
        JOptionPane.showInputDialog("ingresa nombre");
        JOptionPane.showInputDialog("ingresa contraseña");
        JOptionPane.showMessageDialog(null, "usuario creado");
        JOptionPane.showMessageDialog(null, "usuario existente", "ERROR", 0);
    }//GEN-LAST:event_btn_crearPerfilActionPerformed

    private void btn_consultarEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarEstadisticaActionPerformed
        panelConsultaEstadistica p1 = new panelConsultaEstadistica();
        p1.setSize(537,425);
        p1.setLocation(5,5);
        
       
    }//GEN-LAST:event_btn_consultarEstadisticaActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        panelPrincipalOld p1 = new panelPrincipalOld();
        p1.setSize(537,425);
        p1.setLocation(5,5);
        
        
       
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_consultarEstadistica;
    private javax.swing.JButton btn_crearPerfil;
    private javax.swing.JButton btn_exit;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    
    
    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
