/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package othello.view;

import java.util.ArrayList;

/**
 *
 * @author Aleix
 */
public class panelSeleccionarEscenario extends javax.swing.JPanel {
    CtrlView iCtrlView;
    public ArrayList<String> escenarios;
    public int current;

    /**
     * Creates new form panelSeleccionarEscenario
     */
    public panelSeleccionarEscenario(CtrlView pCtrlView) {
        iCtrlView = pCtrlView;
        current = 0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tableroUI1 = new othello.view.TableroUI();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(tableroUI1, gridBagConstraints);

        jLabel1.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(jLabel1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<String> getEscenarios() {
        current = 0;
        return escenarios;
    }

    public void setEscenarios(ArrayList<String> escenarios) {
        this.escenarios = escenarios;
        if(!escenarios.isEmpty()) {
            String[] parts = escenarios.get(current).split(",");
            jLabel1.setText(parts[0]);
            String[] grid = new String[8*8];
            for (int i = 1; i < parts.length; i++) { 
                grid[i-1] = parts[i];
            }
            reloadGrid(grid);
        }
    }
    
    public void fillGrid(String[] grid) {
        int f = 0, s = 0;
        if(grid.length > 0){
            for (String grid1 : grid) {
                tableroUI1.add(new CasillaEscenarioUI(grid1, iCtrlView, f, s));
                if(s == 7) {
                    s = 0;
                    ++f;
                }
                else ++s;
            }
        }
    }
    
    protected void reloadGrid(String[] grid) {
        tableroUI1.clearGrid();
        fillGrid(grid);
    }
    public void resetCurrent() {
        current = 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel jLabel1;
    protected othello.view.TableroUI tableroUI1;
    // End of variables declaration//GEN-END:variables
}
