/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package othello.view;

import java.awt.BorderLayout;



/**
 *
 * @author FRANCO
 */
public class panelConsultaEstadistica extends javax.swing.JPanel {

    
    public panelConsultaEstadistica() {

        initComponents();
        panel_jugador.setVisible(false);
    }

/**
     * Creates new form panelConsultaEstadistica
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_jugador = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_atras = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        box_usuarios = new javax.swing.JComboBox<>();
        label_selecciona = new javax.swing.JLabel();

        jPanel1.setMinimumSize(new java.awt.Dimension(537, 425));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_jugador.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jugador", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        panel_jugador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("EMPATES: nº empates");
        panel_jugador.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 190, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("NOMBRE: id_usuario");
        panel_jugador.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 190, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("PUNTOS: nº puntos");
        panel_jugador.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 190, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("VICTORIAS: nº victorias");
        panel_jugador.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 190, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setText("DERROTAS: nº derrotas");
        panel_jugador.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 190, 30));

        jPanel1.add(panel_jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 320, 280));

        btn_atras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_atras.setText("ATRAS");
        btn_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atrasActionPerformed(evt);
            }
        });
        jPanel1.add(btn_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 90, 30));

        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_exit.setText("EXIT");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 70, 30));

        box_usuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "usuario 1", "usuario 2", "usuario 3", "usuario 5", "usuario 6" }));
        box_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_usuariosActionPerformed(evt);
            }
        });
        jPanel1.add(box_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 70, 20));

        label_selecciona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_selecciona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_selecciona.setText("Selecciona un Usuario");
        jPanel1.add(label_selecciona, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 180, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void box_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_usuariosActionPerformed
        panel_jugador.setVisible(true);
    }//GEN-LAST:event_box_usuariosActionPerformed

    private void btn_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atrasActionPerformed
        /*panelPerfil p1 = new panelPerfil();
        p1.setSize(537,425);
        p1.setLocation(5,5);*/
        
        
        
    }//GEN-LAST:event_btn_atrasActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_usuarios;
    private javax.swing.JButton btn_atras;
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_selecciona;
    private javax.swing.JPanel panel_jugador;
    // End of variables declaration//GEN-END:variables
}
