/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package othello.view;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static othello.view.OthelloUI.panelMain;

/**
 *
 * @author FRANCO
 */
public class panelPrincipal extends javax.swing.JPanel implements ActionListener{

    /**
     * Creates new form principal
     */
    public panelPrincipal() {
        initComponents();
        //jButton1.setIcon(setIcono("src/main/java/resources/barra.jpg",jButton1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btn_perfil = new javax.swing.JButton();
        btn_jugar = new javax.swing.JButton();
        btn_escenario = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        label_othello = new javax.swing.JLabel();
        label_estadistica = new javax.swing.JLabel();
        btn_estadistica = new javax.swing.JButton();

        jPanel1.setMinimumSize(new java.awt.Dimension(537, 425));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_perfil.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_perfil.setText("PERFIL");
        btn_perfil.setMaximumSize(new java.awt.Dimension(180, 60));
        btn_perfil.setMinimumSize(new java.awt.Dimension(180, 60));
        btn_perfil.setPreferredSize(new java.awt.Dimension(180, 60));
        btn_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perfilActionPerformed(evt);
            }
        });
        jPanel1.add(btn_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 125, -1, -1));

        btn_jugar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_jugar.setText("JUGAR");
        btn_jugar.setMaximumSize(new java.awt.Dimension(180, 60));
        btn_jugar.setMinimumSize(new java.awt.Dimension(180, 60));
        btn_jugar.setPreferredSize(new java.awt.Dimension(180, 60));
        jPanel1.add(btn_jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 195, -1, -1));

        btn_escenario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_escenario.setText("ESCENARO");
        btn_escenario.setMaximumSize(new java.awt.Dimension(180, 60));
        btn_escenario.setMinimumSize(new java.awt.Dimension(180, 60));
        btn_escenario.setPreferredSize(new java.awt.Dimension(180, 60));
        jPanel1.add(btn_escenario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 265, -1, -1));

        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_exit.setText("EXIT");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 89, -1));

        label_othello.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 60)); // NOI18N
        label_othello.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_othello.setText("OTHELLO");
        label_othello.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(label_othello, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 37, 288, 82));

        label_estadistica.setText("Estadistica");
        jPanel1.add(label_estadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 118, -1, -1));

        btn_estadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estadisticaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_estadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 70, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perfilActionPerformed
        panelPerfil p1 = new panelPerfil();
        p1.setSize(537,425);
        p1.setLocation(5,5);
        
        
        panelMain.removeAll();
        panelMain.add(p1,BorderLayout.CENTER);
        panelMain.revalidate();
        panelMain.repaint();
    }//GEN-LAST:event_btn_perfilActionPerformed

    private void btn_estadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estadisticaActionPerformed
        panelRanking p1 = new panelRanking();
        p1.setSize(537,425);
        p1.setLocation(5,5);
        
        
        panelMain.removeAll();
        panelMain.add(p1,BorderLayout.CENTER);
        panelMain.revalidate();
        panelMain.repaint();
    }//GEN-LAST:event_btn_estadisticaActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    
    /*public Icon setIcono(String url, JButton boton){
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto,Image.SCALE_DEFAULT));
        
        return icono;
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_escenario;
    private javax.swing.JButton btn_estadistica;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_jugar;
    private javax.swing.JButton btn_perfil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_estadistica;
    private javax.swing.JLabel label_othello;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
