package othello.view;

import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Aleix
 */
public class TableroUI extends JPanel {

    /**
     * Creates new form TableroUI
     */
    public TableroUI() {
        initComponents();
        
    }

    /**
     * 
     * @param grid 
     */
    public void fillGrid(ArrayList<ArrayList<Integer>> grid) {
        for (int i = 0; i < grid.size(); i++) {
            for (int j = 0; j < grid.get(i).size(); j++) {
                this.add(new CasillaUI(grid.get(i).get(j)));
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(23, 113, 43));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        setLayout(new java.awt.GridLayout(8, 8));
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
